// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Quote struct {
	ID                    string
	Text                  string
	Author                string
	NormalizedFingerprint string
	CreatedAtUtc          time.Time
}
