// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countQuotes = `-- name: CountQuotes :one
SELECT COUNT(*) FROM quotes
`

func (q *Queries) CountQuotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuoteById = `-- name: GetQuoteById :one
SELECT id, text, author, normalized_fingerprint, created_at_utc
FROM quotes
WHERE id = $1
`

func (q *Queries) GetQuoteById(ctx context.Context, id string) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteById, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Author,
		&i.NormalizedFingerprint,
		&i.CreatedAtUtc,
	)
	return i, err
}

const getRandomQuote = `-- name: GetRandomQuote :one

SELECT id, text, author, normalized_fingerprint, created_at_utc
FROM quotes
ORDER BY random()
LIMIT 1
`

// The catalog's reviewed SQL (ADR 0007): the query text is the artifact, the
// .NET adapter's EF/raw-query semantics ported one statement at a time.
// Random pick happens inside PostgreSQL — exact parity with the EF FromSql
// raw query. The catalog is PoC-sized, so a full sort per pick is the simple,
// correct tool. An empty catalog surfaces as pgx.ErrNoRows in the adapter.
func (q *Queries) GetRandomQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRow(ctx, getRandomQuote)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Author,
		&i.NormalizedFingerprint,
		&i.CreatedAtUtc,
	)
	return i, err
}

const insertQuote = `-- name: InsertQuote :exec
INSERT INTO quotes (id, text, author, normalized_fingerprint, created_at_utc)
VALUES ($1, $2, $3, $4, $5)
`

type InsertQuoteParams struct {
	ID                    string
	Text                  string
	Author                string
	NormalizedFingerprint string
	CreatedAtUtc          time.Time
}

// Plain INSERT on purpose: duplicate detection leans on the unique
// normalized_fingerprint index instead of a check-then-insert race — a
// colliding insert fails with PostgreSQL error 23505, which the adapter maps
// to the QuoteDuplicateFingerprint outcome.
func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) error {
	_, err := q.db.Exec(ctx, insertQuote,
		arg.ID,
		arg.Text,
		arg.Author,
		arg.NormalizedFingerprint,
		arg.CreatedAtUtc,
	)
	return err
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, text, author, normalized_fingerprint, created_at_utc
FROM quotes
ORDER BY created_at_utc, id
LIMIT $1 OFFSET $2
`

type ListQuotesParams struct {
	Limit  int32
	Offset int32
}

// Stable catalog order: seeds first (they share a fixed timestamp), then
// created quotes in creation order, with the id as a deterministic tiebreaker.
func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Author,
			&i.NormalizedFingerprint,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
