// Contract for this quote transport, served by ASP.NET Core's stock gRPC-JSON transcoding
// (Microsoft.AspNetCore.Grpc.JsonTranscoding): the google.api.http rules below drive the
// routing themselves — no adapter endpoints exist. The behavior is the platform runtime's
// own and is pinned by tests: error bodies are the gRPC status envelope
// ({"code","message","details"}) and create answers 200 without a Location header.
// Paging scalars are declared `optional` so transcoding's JSON writer emits them even at
// proto defaults (page = 1); without explicit presence they would be omitted from every
// first-page response.
//
// The OpenAPI document for this transport is GENERATED from this file — the comments, the
// google.api.http rules and the openapiv2 options below, via protoc-gen-openapiv2 driven
// by buf — and served at /openapi/v3.json, so the proto stays the single contract of
// record. (The generator emits Swagger 2.0; no maintained generator produces OpenAPI 3
// from google.api.http rules.)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: quotes_v3.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuoteService_ListQuotes_FullMethodName     = "/quotes.v3.QuoteService/ListQuotes"
	QuoteService_GetQuoteById_FullMethodName   = "/quotes.v3.QuoteService/GetQuoteById"
	QuoteService_GetRandomQuote_FullMethodName = "/quotes.v3.QuoteService/GetRandomQuote"
	QuoteService_CreateQuote_FullMethodName    = "/quotes.v3.QuoteService/CreateQuote"
)

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteServiceClient interface {
	// Lists one page of the quote catalog in stable order. Fields not bound by the path
	// (page, pageSize) travel as query parameters.
	ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error)
	// Returns one quote by id.
	GetQuoteById(ctx context.Context, in *GetQuoteByIdRequest, opts ...grpc.CallOption) (*Quote, error)
	// Returns a random quote from the catalog.
	GetRandomQuote(ctx context.Context, in *GetRandomQuoteRequest, opts ...grpc.CallOption) (*Quote, error)
	// Adds a quote to the catalog; the request body maps onto the whole message. Answers
	// 200 with the created quote — transcoding has no way to express 201 + Location.
	CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*Quote, error)
}

type quoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteServiceClient(cc grpc.ClientConnInterface) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuotesResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuoteById(ctx context.Context, in *GetQuoteByIdRequest, opts ...grpc.CallOption) (*Quote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quote)
	err := c.cc.Invoke(ctx, QuoteService_GetQuoteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetRandomQuote(ctx context.Context, in *GetRandomQuoteRequest, opts ...grpc.CallOption) (*Quote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quote)
	err := c.cc.Invoke(ctx, QuoteService_GetRandomQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*Quote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quote)
	err := c.cc.Invoke(ctx, QuoteService_CreateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
// All implementations must embed UnimplementedQuoteServiceServer
// for forward compatibility.
type QuoteServiceServer interface {
	// Lists one page of the quote catalog in stable order. Fields not bound by the path
	// (page, pageSize) travel as query parameters.
	ListQuotes(context.Context, *ListQuotesRequest) (*ListQuotesResponse, error)
	// Returns one quote by id.
	GetQuoteById(context.Context, *GetQuoteByIdRequest) (*Quote, error)
	// Returns a random quote from the catalog.
	GetRandomQuote(context.Context, *GetRandomQuoteRequest) (*Quote, error)
	// Adds a quote to the catalog; the request body maps onto the whole message. Answers
	// 200 with the created quote — transcoding has no way to express 201 + Location.
	CreateQuote(context.Context, *CreateQuoteRequest) (*Quote, error)
	mustEmbedUnimplementedQuoteServiceServer()
}

// UnimplementedQuoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuoteServiceServer struct{}

func (UnimplementedQuoteServiceServer) ListQuotes(context.Context, *ListQuotesRequest) (*ListQuotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuotes not implemented")
}
func (UnimplementedQuoteServiceServer) GetQuoteById(context.Context, *GetQuoteByIdRequest) (*Quote, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuoteById not implemented")
}
func (UnimplementedQuoteServiceServer) GetRandomQuote(context.Context, *GetRandomQuoteRequest) (*Quote, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomQuote not implemented")
}
func (UnimplementedQuoteServiceServer) CreateQuote(context.Context, *CreateQuoteRequest) (*Quote, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) mustEmbedUnimplementedQuoteServiceServer() {}
func (UnimplementedQuoteServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServiceServer will
// result in compilation errors.
type UnsafeQuoteServiceServer interface {
	mustEmbedUnimplementedQuoteServiceServer()
}

func RegisterQuoteServiceServer(s grpc.ServiceRegistrar, srv QuoteServiceServer) {
	// If the following call panics, it indicates UnimplementedQuoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuoteService_ServiceDesc, srv)
}

func _QuoteService_ListQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListQuotes(ctx, req.(*ListQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuoteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuoteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_GetQuoteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuoteById(ctx, req.(*GetQuoteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetRandomQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetRandomQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_GetRandomQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetRandomQuote(ctx, req.(*GetRandomQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_CreateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_CreateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateQuote(ctx, req.(*CreateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteService_ServiceDesc is the grpc.ServiceDesc for QuoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quotes.v3.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListQuotes",
			Handler:    _QuoteService_ListQuotes_Handler,
		},
		{
			MethodName: "GetQuoteById",
			Handler:    _QuoteService_GetQuoteById_Handler,
		},
		{
			MethodName: "GetRandomQuote",
			Handler:    _QuoteService_GetRandomQuote_Handler,
		},
		{
			MethodName: "CreateQuote",
			Handler:    _QuoteService_CreateQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotes_v3.proto",
}
