// Contract for this quote transport, served by ASP.NET Core's stock gRPC-JSON transcoding
// (Microsoft.AspNetCore.Grpc.JsonTranscoding): the google.api.http rules below drive the
// routing themselves — no adapter endpoints exist. The behavior is the platform runtime's
// own and is pinned by tests: error bodies are the gRPC status envelope
// ({"code","message","details"}) and create answers 200 without a Location header.
// Paging scalars are declared `optional` so transcoding's JSON writer emits them even at
// proto defaults (page = 1); without explicit presence they would be omitted from every
// first-page response.
//
// The OpenAPI document for this transport is GENERATED from this file — the comments, the
// google.api.http rules and the openapiv2 options below, via protoc-gen-openapiv2 driven
// by buf — and served at /openapi/v3.json, so the proto stays the single contract of
// record. (The generator emits Swagger 2.0; no maintained generator produces OpenAPI 3
// from google.api.http rules.)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: quotes_v3.proto

package contractv3

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A quote as served to an authenticated client.
type Quote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable quote identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Quote body text.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Attributed author of the quote.
	Author        string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_quotes_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{0}
}

func (x *Quote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Quote) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type GetRandomQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuoteRequest) Reset() {
	*x = GetRandomQuoteRequest{}
	mi := &file_quotes_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuoteRequest) ProtoMessage() {}

func (x *GetRandomQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{1}
}

type GetQuoteByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quote identifier as returned by create or list.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteByIdRequest) Reset() {
	*x = GetQuoteByIdRequest{}
	mi := &file_quotes_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteByIdRequest) ProtoMessage() {}

func (x *GetQuoteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteByIdRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteByIdRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListQuotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based page number (minimum 1).
	Page *int32 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// Items per page, between 1 and 100 (default 20).
	PageSize      *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesRequest) Reset() {
	*x = ListQuotesRequest{}
	mi := &file_quotes_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesRequest) ProtoMessage() {}

func (x *ListQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesRequest.ProtoReflect.Descriptor instead.
func (*ListQuotesRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{3}
}

func (x *ListQuotesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListQuotesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

// Payload to add a quote to the catalog.
type CreateQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quote body text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Attributed author of the quote.
	Author        string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuoteRequest) Reset() {
	*x = CreateQuoteRequest{}
	mi := &file_quotes_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteRequest) ProtoMessage() {}

func (x *CreateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteRequest.ProtoReflect.Descriptor instead.
func (*CreateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQuoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateQuoteRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// One page of the quote catalog.
type ListQuotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quotes on this page, in stable catalog order.
	Items []*Quote `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 1-based page number this response represents.
	Page *int32 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// Number of items per page that was requested.
	PageSize *int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Total number of quotes in the catalog.
	TotalItems *int32 `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3,oneof" json:"total_items,omitempty"`
	// Total number of pages at the requested page size.
	TotalPages    *int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3,oneof" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesResponse) Reset() {
	*x = ListQuotesResponse{}
	mi := &file_quotes_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesResponse) ProtoMessage() {}

func (x *ListQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesResponse.ProtoReflect.Descriptor instead.
func (*ListQuotesResponse) Descriptor() ([]byte, []int) {
	return file_quotes_v3_proto_rawDescGZIP(), []int{5}
}

func (x *ListQuotesResponse) GetItems() []*Quote {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListQuotesResponse) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListQuotesResponse) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListQuotesResponse) GetTotalItems() int32 {
	if x != nil && x.TotalItems != nil {
		return *x.TotalItems
	}
	return 0
}

func (x *ListQuotesResponse) GetTotalPages() int32 {
	if x != nil && x.TotalPages != nil {
		return *x.TotalPages
	}
	return 0
}

var File_quotes_v3_proto protoreflect.FileDescriptor

const file_quotes_v3_proto_rawDesc = "" +
	"\n" +
	"\x0fquotes_v3.proto\x12\tquotes.v3\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"C\n" +
	"\x05Quote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\"\x17\n" +
	"\x15GetRandomQuoteRequest\"%\n" +
	"\x13GetQuoteByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x11ListQuotesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"@\n" +
	"\x12CreateQuoteRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\"\xfa\x01\n" +
	"\x12ListQuotesResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.quotes.v3.QuoteR\x05items\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12$\n" +
	"\vtotal_items\x18\x04 \x01(\x05H\x02R\n" +
	"totalItems\x88\x01\x01\x12$\n" +
	"\vtotal_pages\x18\x05 \x01(\x05H\x03R\n" +
	"totalPages\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\x0e\n" +
	"\f_total_itemsB\x0e\n" +
	"\f_total_pages2\x90\x03\n" +
	"\fQuoteService\x12a\n" +
	"\n" +
	"ListQuotes\x12\x1c.quotes.v3.ListQuotesRequest\x1a\x1d.quotes.v3.ListQuotesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v3/quotes\x12]\n" +
	"\fGetQuoteById\x12\x1e.quotes.v3.GetQuoteByIdRequest\x1a\x10.quotes.v3.Quote\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v3/quotes/{id}\x12c\n" +
	"\x0eGetRandomQuote\x12 .quotes.v3.GetRandomQuoteRequest\x1a\x10.quotes.v3.Quote\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v3/quotes/random\x12Y\n" +
	"\vCreateQuote\x12\x1d.quotes.v3.CreateQuoteRequest\x1a\x10.quotes.v3.Quote\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v3/quotesB\x92\x06\x92A\xb3\x05\x12\x82\x04\n" +
	"\x0fQuotes.Api | v3\x12\xe7\x03Quote catalog for the Aspire Quotes platform, served by stock gRPC-JSON transcoding: the google.api.http rules in this contract drive the routing.\n" +
	"\n" +
	"Every error response is the gRPC status envelope {code, message, details}; the machine-readable errorCode does not travel. Create answers 200 with the created quote and no Location header. Pagination is 1-based (page from 1, pageSize between 1 and 100, default 20). Send X-Correlation-Id to correlate calls; it is echoed on every response.2\x051.0.0Z\x9d\x01\n" +
	"\x9a\x01\n" +
	"\x06Bearer\x12\x8f\x01\b\x02\x12zBearer JWT from the Auth API (POST /api/v1/auth/login). Reads require the quotes:read scope; create requires quotes:write.\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00ZYgithub.com/josnelihurt/code.examples.go.quotes/internal/quotes/api/v3/contract;contractv3b\x06proto3"

var (
	file_quotes_v3_proto_rawDescOnce sync.Once
	file_quotes_v3_proto_rawDescData []byte
)

func file_quotes_v3_proto_rawDescGZIP() []byte {
	file_quotes_v3_proto_rawDescOnce.Do(func() {
		file_quotes_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quotes_v3_proto_rawDesc), len(file_quotes_v3_proto_rawDesc)))
	})
	return file_quotes_v3_proto_rawDescData
}

var file_quotes_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quotes_v3_proto_goTypes = []any{
	(*Quote)(nil),                 // 0: quotes.v3.Quote
	(*GetRandomQuoteRequest)(nil), // 1: quotes.v3.GetRandomQuoteRequest
	(*GetQuoteByIdRequest)(nil),   // 2: quotes.v3.GetQuoteByIdRequest
	(*ListQuotesRequest)(nil),     // 3: quotes.v3.ListQuotesRequest
	(*CreateQuoteRequest)(nil),    // 4: quotes.v3.CreateQuoteRequest
	(*ListQuotesResponse)(nil),    // 5: quotes.v3.ListQuotesResponse
}
var file_quotes_v3_proto_depIdxs = []int32{
	0, // 0: quotes.v3.ListQuotesResponse.items:type_name -> quotes.v3.Quote
	3, // 1: quotes.v3.QuoteService.ListQuotes:input_type -> quotes.v3.ListQuotesRequest
	2, // 2: quotes.v3.QuoteService.GetQuoteById:input_type -> quotes.v3.GetQuoteByIdRequest
	1, // 3: quotes.v3.QuoteService.GetRandomQuote:input_type -> quotes.v3.GetRandomQuoteRequest
	4, // 4: quotes.v3.QuoteService.CreateQuote:input_type -> quotes.v3.CreateQuoteRequest
	5, // 5: quotes.v3.QuoteService.ListQuotes:output_type -> quotes.v3.ListQuotesResponse
	0, // 6: quotes.v3.QuoteService.GetQuoteById:output_type -> quotes.v3.Quote
	0, // 7: quotes.v3.QuoteService.GetRandomQuote:output_type -> quotes.v3.Quote
	0, // 8: quotes.v3.QuoteService.CreateQuote:output_type -> quotes.v3.Quote
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quotes_v3_proto_init() }
func file_quotes_v3_proto_init() {
	if File_quotes_v3_proto != nil {
		return
	}
	file_quotes_v3_proto_msgTypes[3].OneofWrappers = []any{}
	file_quotes_v3_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quotes_v3_proto_rawDesc), len(file_quotes_v3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quotes_v3_proto_goTypes,
		DependencyIndexes: file_quotes_v3_proto_depIdxs,
		MessageInfos:      file_quotes_v3_proto_msgTypes,
	}.Build()
	File_quotes_v3_proto = out.File
	file_quotes_v3_proto_goTypes = nil
	file_quotes_v3_proto_depIdxs = nil
}
